export default {
  "initialParams": {
    "url": "http://undefined",
    "profileId": "2025",
    "agentId": "42643",
    "agentUsername": "clt.fatimah.smith",
    "callId": "300138578820190612",
    "environment": "test",
    "coreUrl": "https://dev.reactor-core.redventures.net",
    "jwt": "redacted",
    "ropeId": "R5d013a345bed5925703665ltXwU2025",
    "dataOnly": "1"
  },
  "environment": {
    "environment": "test",
    "prefix": "test-",
    "vars": {}
  },
  "profileId": "2025",
  "agentId": "42643",
  "agentUsername": "clt.fatimah.smith",
  "callId": "300138578820190612",
  "coreUrl": "https://dev.reactor-core.redventures.net",
  "rope": {
    "ropeId": "R5d013a345bed5925703665ltXwU2025"
  },
  "call": {
    "id": "38236961",
    "callId": "300138578820190612",
    "confCallId": null,
    "callDirection": "Inbound",
    "callDateTime": "2019-06-12 12:44:17",
    "callDate": "2019-06-12",
    "callLength": "0",
    "dnis": "8444534165",
    "marketingCodeId": "3536754",
    "marketingProgramId": "1270721",
    "subCompanyId": "53",
    "affiliateId": "0",
    "channelId": "5",
    "marketingCategoryId": "4308",
    "contactId": null,
    "callerId_number": "4437845220",
    "callerId_name": "paid-vz-fivz-google-mobile-nt-brand-baltimore; WIRELESS CALLER",
    "initialWorkgroup": "Verizon_Sales",
    "language": "",
    "callType": "Sales Inbound",
    "callReference": null,
    "phoneSystemSiteId": "2",
    "conversionExclude": "0",
    "manualScheduleId": null,
    "callsCompanies": {
      "0": {
        "callCompanyId": "44362812",
        "id": "38236961",
        "companyId": "54",
        "dispositionId": "5692",
        "agentId": "42643",
        "leadId": null,
        "workGroup": "Verizon_Sales",
        "callNotes": "",
        "dateTimeAdded": "2019-06-12 12:45:23",
        "dateAdded": "2019-06-12",
        "lastUpdated": null,
        "___type": null,
        "_self": null
      }
    },
    "ivrEvents": {
      "autorouting": "Level1",
      "holdloggedinratio": "0.0"
    },
    "remote": "4437845220",
    "callApplicationId": "2",
    "dateAdded": null,
    "dateTimeAdded": null,
    "lastUpdated": null,
    "___type": null,
    "_self": null,
    "programName": "paid-vz-fivz-google-mobile-nt-brand-baltimore",
    "channelName": "Online Paid Search",
    "marketingGreeting": ""
  },
  "agent": {
    "agentId": 42643,
    "phoneSystemSiteId": 13,
    "callCenterLocationId": 2,
    "agentSupervisorId": 613,
    "agentCategoryId": 1,
    "agentTypeId": 1,
    "username": "clt.fatimah.smith",
    "password": null,
    "firstName": "Fatimah",
    "lastName": "Smith",
    "nickName": "",
    "hireDate": "2018-06-18",
    "firstCallDate": "2019-05-13",
    "dOBMonth": null,
    "dOBDay": null,
    "active": 1,
    "oldAgentId": null,
    "oldUsername": null,
    "manualSchedule": "n",
    "employmentStatus": "FT",
    "shift": "AM",
    "position": null,
    "developer": "n",
    "redVisorDisplay": "y",
    "leadStatusCompanyId": null,
    "agentImage": "",
    "probation": "n",
    "allconnectAgentId": null,
    "agentClassId": 3432,
    "dIRECTVAgentId": null,
    "iPOSFlag": null,
    "payroll": null,
    "loggedInDialer": 0,
    "lunchBreak": 1800,
    "previousAgentId": null,
    "homePhone": "",
    "cellPhone": "",
    "homeLandline": null,
    "homeBroadband": null,
    "homePC": null,
    "homeEmailAddress": null,
    "workEmailAddress": null,
    "orvisEmailAddress": null,
    "orvisEmailFromName": null,
    "terminationDate": null,
    "gender": null,
    "phoneSystemExtension": 77515,
    "isTrainingAccount": 0,
    "employeeId": 24885,
    "primaryCompanyId": 54,
    "createdByIntranetUserId": 2117,
    "supervisorId": null,
    "supervisorUserName": null,
    "flags": [
      456
    ],
    "dateAdded": null,
    "dateTimeAdded": "2019-05-08 11:10:16",
    "lastUpdated": null,
    "___type": "Atom\\SharedAPI\\Model\\Agent",
    "token": "redacted"
  },
  "reactor": {
    "coreUrl": "https://dev.reactor-core.redventures.net"
  },
  "profile": {
    "profileId": "2025",
    "name": "Verizon",
    "shortName": "Verizon",
    "description": "Verizon Default Profile",
    "icon": "https://ss7.vzw.com/is/image/VerizonWireless/vzw-logo-156-130-c?$pngalpha$&wid=640&hei=400",
    "atomConfig": {
      "decreeApiKey": "12fb0c0b-33f3-c7ba-bc36-da26541bc19e",
      "fullstory": 1,
      "fullstoryOrgKey": "9YAYP",
      "launcherUrl": "https://{corePrefix}core.atom.rvapps.io/launcher",
      "enablePipeline": 1
    },
    "reactorConfig": "{\"configPath\":\"\\/usr\\/share\\/www\\/src\\/react\\/neutron\\/src\\/configuration\\/default.json\",\"atomUrl\":\"http:\\/\\/atom.redventures.net?profileId=2025&\"}",
    "ropeConfig": {
      "applicationProfileId": 2025,
      "apiKeys": null,
      "companies": [
        54
      ],
      "primaryCompanyId": 54,
      "companyId": 54,
      "shardId": 31,
      "shard": "Verizon",
      "ropeDatabase": "Verizon_Rope",
      "companyDatabase": "Verizon",
      "logo": "https://ss7.vzw.com/is/image/VerizonWireless/vzw-logo-156-130-c?$pngalpha$&wid=640&hei=400",
      "mpsSource": "MPS_Context_Verizon",
      "description": "Verizon Default Profile",
      "config": null,
      "companySettings": null,
      "dateAdded": null,
      "dateTimeAdded": null,
      "lastUpdated": null,
      "___type": "Rope\\Model\\ApplicationProfile"
    },
    "atom": "1",
    "reactor": "1",
    "rope": "0",
    "isDefault": "0",
    "primaryCompanyId": "54",
    "agentAssignable": "1",
    "parentProfileId": "2025",
    "constName": "VERIZON",
    "profileCompanies": [],
    "dateAdded": "2016-01-12",
    "dateTimeAdded": "2016-01-12 00:00:00",
    "lastUpdated": "2019-01-30 10:53:54",
    "___type": null,
    "_self": null,
    "primaryCompany": {
      "companyId": "54",
      "shardId": "31",
      "shardName": "Verizon",
      "companyName": "Verizon",
      "databaseName": "Verizon",
      "companyPrefix": "vz",
      "queuePrefix": "Verizon",
      "serverPodId": "3",
      "serverPod": "p03"
    }
  },
  "callsCompanies": {
    "0": {
      "callCompanyId": "44362812",
      "id": "38236961",
      "companyId": "54",
      "dispositionId": "5692",
      "agentId": "42643",
      "leadId": null,
      "workGroup": "Verizon_Sales",
      "callNotes": "",
      "dateTimeAdded": "2019-06-12 12:45:23",
      "dateAdded": "2019-06-12",
      "lastUpdated": null,
      "___type": null,
      "_self": null
    }
  },
  "profileRules": {
    "profileRulesId": 18,
    "profileId": 2025,
    "userName": "pgordon",
    "ruleLink": "",
    "ruleName": "PROFILE-ID-2025-SCENARIO-RULES",
    "ruleCollection": "{\"RuleName\":\"PROFILE-ID-2025-SCENARIO-RULES\",\"DisplayName\":\"\",\"RuleDescription\":\"\",\"RuleSets\":[{\"Operator\":\"\",\"OnTrue\":{\"Value\":\"5691\",\"Type\":\"Scenario\"},\"Rule\":[{\"PropertyToEvaluate\":\"\",\"Rule\":\"\",\"EvaluateTo\":\"\",\"GUID\":\"3529367b-197a-5d69-e020-27725ca5f7c0\"}],\"GUID\":\"ac9383d6-eed6-55ed-ae5a-10ded0cd8f1d\"},{\"GUID\":\"6954d7c2-8666-03b7-1a89-9db67869a2d4\",\"Operator\":\"And\",\"OnTrue\":{\"Type\":\"Scenario\",\"Value\":\"5570\"},\"Rule\":[{\"PropertyToEvaluate\":\"agent.agentId\",\"Rule\":\"contains\",\"EvaluateTo\":\"42479,33411,30232\",\"GUID\":\"d8cdee82-4ed8-65c6-78a7-70a493a9a1a7\"}]},{\"GUID\":\"e13b370c-c906-9264-a0fd-03b5522d6f9c\",\"Operator\":\"And\",\"OnTrue\":{\"Type\":\"Scenario\",\"Value\":\"5570\"},\"Rule\":[{\"PropertyToEvaluate\":\"agent.agentId\",\"Rule\":\"contains\",\"EvaluateTo\":\"42043,42334,19804,24812\",\"GUID\":\"906fac11-44f4-b01f-12b8-82acd565182c\"}]},{\"GUID\":\"bc75a076-bdca-319d-bff6-ef283e57bf72\",\"Operator\":\"And\",\"OnTrue\":{\"Type\":\"Scenario\",\"Value\":\"5691\"},\"Rule\":[{\"PropertyToEvaluate\":\"agent.flags\",\"Rule\":\"contains\",\"EvaluateTo\":\"919\",\"GUID\":\"b864ad89-92b7-0809-e2d8-d683632daaf4\"}]}],\"apikey\":\"12fb0c0b-33f3-c7ba-bc36-da26541bc19e\"}",
    "dateAdded": "2018-04-03",
    "dateTimeAdded": "2018-04-03 22:15:31",
    "lastUpdated": "2019-06-10 14:19:37",
    "___type": "Atom\\SharedAPI\\Model\\ProfileRules"
  },
  "marketing": {
    "marketingCodeId": "3536754",
    "marketingProgramId": "1270721",
    "affiliateId": "0",
    "channelId": "5"
  },
  "contact": {},
  "serviceable": {},
  "scenario": {
    "scenarioId": 5691,
    "tagId": null
  }
}
