version: 2.1

references:
  container_config: &container_config
    docker:
      - image: circleci/node:10
  base_filter: &base_filter
    filters:
      tags:
        only: /^.*/
  tag_filter: &tag_filter
    filters:
      branches:
        ignore: /.*/
      tags:
        only: /^.*/

orbs:
  aws-cli: circleci/aws-cli@0.1.13

jobs:
  aws_config:
    <<: *container_config
    executor: aws-cli/default
    steps:
      - aws-cli/install
      - run:
          name: Setup variables
          command: |
            echo 'if [ $CIRCLE_BRANCH != "development" && $CIRCLE_BRANCH != "master" && $CIRCLE_BRANCH != "test" && $CIRCLE_BRANCH != "uat" ] then KEYENV=DEVELOPMENT && BRANCH=development' >> aws_config
            echo 'if [ $CIRCLE_BRANCH == "development" ] || [ $CIRCLE_BRANCH == "master" ] || [ $CIRCLE_BRANCH == "test" ] || [ $CIRCLE_BRANCH == "uat" ] then KEYENV=$( echo $CIRCLE_BRANCH | tr "[:lower:]" "[:upper:]" ) && BRANCH=$CIRCLE_BRANCH fi' >> aws_config
            echo 'ACCESS_KEY="AWS_ACCESS_KEY_ID_$KEYENV"' >> aws_config
            echo 'SECRET_KEY="AWS_SECRET_ACCESS_KEY_$KEYENV"' >> aws_config
            echo 'aws configure set aws_access_key_id "${!ACCESS_KEY}" --profile default' >> aws_config
            echo 'aws configure set aws_secret_access_key "${!SECRET_KEY}" --profile default' >> aws_config
            echo 'aws configure set region us-east-1 --profile default' >> aws_config
            echo 'if [[ $CIRCLE_BRANCH != "master" ]] then export CIRCLE_LD_KEY=$TEST_LD_SDK_KEY; else export CIRCLE_LD_KEY=$PROD_LD_SDK_KEY fi' >> aws_config       
      - persist_to_workspace:
          root: .
          paths:
            - aws_config
  sync:
    <<: *container_config
    executor: aws-cli/default
    steps:
      - aws-cli/install
      - attach_workspace:
          at: .
      - run: cat aws_config >> $BASH_ENV
      - run:
          name: Configure AWS CLI
          command: |
            aws s3 ls
  deploy:
    <<: *container_config
    executor: aws-cli/default
    steps:
      - aws-cli/install
      - attach_workspace:
          at: .
      - run: cat aws_config >> $BASH_ENV
      - run:
          name: deploy Lambda
          command: |
            aws lambda update-function-configuration --function-name $CIRCLE_PROJECT_REPONAME-$BRANCH --environment Variables="{LAUNCHDARKLY_KEY=$CIRCLE_LD_KEY,ENVIRONMENT=$BRANCH,NODE_ENV=$BRANCH}"       
            aws lambda update-function-code --function-name $CIRCLE_PROJECT_REPONAME-$BRANCH --s3-bucket atom-shield-build-artifacts-$BRANCH-us-east-1 --s3-key $CIRCLE_PROJECT_REPONAME-$CIRCLE_TAG.zip
            aws lambda publish-version --function-name $CIRCLE_PROJECT_REPONAME-$BRANCH
            aws lambda update-alias --function-name $CIRCLE_PROJECT_REPONAME-$BRANCH --name "live" --function-version '$LATEST'
 
workflows:
  version: 2
  default-workflow:
    jobs:
      - aws_config
      - sync:
          requires:
            - aws_config
          <<: *base_filter
      # - deploy:
      #     requires:
      #       - sync
      #       - aws_config
      #     <<: *base_filter
